version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: gender
        tests:
          - accepted_values:
              values: ['M', 'F']
                

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['Complete', 'Cancelled', 'Returned']
      - name: order_date
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: department
        tests:
          - accepted_values:
              values: ['Men', 'Women']