version: 2

sources:
    - name: ecommerce
      description: This is a replica of the snowflake database used by our app
      database: DB_VN252_NS
      schema: ECOMM_SCHEMA
      tables:
          - name: customers
            description: One record per customer.
            columns:
              - name: id
                data_type: number
              - name: first_name
                data_type: varchar
              - name: last_name
                data_type: varchar
              - name: email
                data_type: varchar
              - name: gender
                data_type: varchar
              - name: country
                data_type: varchar

          - name: orders
            description: One record per order. Includes cancelled and deleted orders.
            columns:
              - name: order_id
                data_type: number
              - name: user_id
                data_type: number
              - name: product_id
                data_type: number
              - name: status
                data_type: varchar
              - name: created_at
                data_type: varchar
              - name: delivered_at
                data_type: varchar
              - name: returned_at
                data_type: varchar
              - name: sales_value
                data_type: number
              - name: quantity
                data_type: number
        
          - name: products
            description: One record per order.
            columns:
              - name: id
                data_type: number
              - name: category
                data_type: varchar
              - name: name
                data_type: varchar
              - name: brand
                data_type: varchar
              - name: rrp
                data_type: number
              - name: department
                data_type: varchar
              - name: sku
                data_type: varchar